---
name: Call Trivy
on:
 push:
   branches: [main]
 pull_request:
 workflow_run:
  workflows: ["Docker Build"]
  types:
    - completed

jobs:
  scan:
    name: Scan
    uses: muir-island/actions/.github/workflows/reusable-trivy.yml@main
    with:
      image: 'ghcr.io/muir-island/wordsmith-web:latest'