name: Call Trivy
on:
 push:
   branches: [main]
 pull_request:
jobs:
 scan:
   name: Scan
   uses: muir-island/actions/.github/workflows/reusable-trivy.yml@reusuable-workflow
   with:
    image: 'ghcr.io/muir-island/wordsmith-web:pr-7'